/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-vehicle`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/fuel-history/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/colors`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/index`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/add-fueling/fuel-input`; params?: Router.UnknownInputParams; } | { pathname: `/add-fueling/odometer-input`; params?: Router.UnknownInputParams; } | { pathname: `/add-fueling/station-selection`; params?: Router.UnknownInputParams; } | { pathname: `/add-fueling/summary`; params?: Router.UnknownInputParams; } | { pathname: `/fuel-history/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/vehicle-details/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/vehicle-history/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-vehicle`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/fuel-history/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/add-fueling/fuel-input`; params?: Router.UnknownOutputParams; } | { pathname: `/add-fueling/odometer-input`; params?: Router.UnknownOutputParams; } | { pathname: `/add-fueling/station-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/add-fueling/summary`; params?: Router.UnknownOutputParams; } | { pathname: `/fuel-history/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/vehicle-details/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/vehicle-history/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-vehicle${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/fuel-history/[id]${`?${string}` | `#${string}` | ''}` | `/../constants/colors${`?${string}` | `#${string}` | ''}` | `/../constants/index${`?${string}` | `#${string}` | ''}` | `/../constants/theme${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/add-fueling/fuel-input${`?${string}` | `#${string}` | ''}` | `/add-fueling/odometer-input${`?${string}` | `#${string}` | ''}` | `/add-fueling/station-selection${`?${string}` | `#${string}` | ''}` | `/add-fueling/summary${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-vehicle`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/fuel-history/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/colors`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/index`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/add-fueling/fuel-input`; params?: Router.UnknownInputParams; } | { pathname: `/add-fueling/odometer-input`; params?: Router.UnknownInputParams; } | { pathname: `/add-fueling/station-selection`; params?: Router.UnknownInputParams; } | { pathname: `/add-fueling/summary`; params?: Router.UnknownInputParams; } | `/fuel-history/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/vehicle-details/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/vehicle-history/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/fuel-history/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/vehicle-details/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/vehicle-history/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
